# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addRegisterCobranza.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Cobranzas(object):
    def setupUi(self, Cobranzas):
        Cobranzas.setObjectName(_fromUtf8("Cobranzas"))
        Cobranzas.resize(594, 384)
        self.horizontalLayout_11 = QtGui.QHBoxLayout(Cobranzas)
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(Cobranzas)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.comboBoxTipoRegistro = QtGui.QComboBox(Cobranzas)
        self.comboBoxTipoRegistro.setObjectName(_fromUtf8("comboBoxTipoRegistro"))
        self.horizontalLayout.addWidget(self.comboBoxTipoRegistro)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(Cobranzas)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.cmpFechaRegistro = QtGui.QLineEdit(Cobranzas)
        self.cmpFechaRegistro.setObjectName(_fromUtf8("cmpFechaRegistro"))
        self.horizontalLayout_2.addWidget(self.cmpFechaRegistro)
        self.label_FechaRegistro = QtGui.QLabel(Cobranzas)
        self.label_FechaRegistro.setText(_fromUtf8(""))
        self.label_FechaRegistro.setObjectName(_fromUtf8("label_FechaRegistro"))
        self.horizontalLayout_2.addWidget(self.label_FechaRegistro)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_3 = QtGui.QLabel(Cobranzas)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cmpConcepto = QtGui.QLineEdit(Cobranzas)
        self.cmpConcepto.setObjectName(_fromUtf8("cmpConcepto"))
        self.horizontalLayout_3.addWidget(self.cmpConcepto)
        self.label_Concepto = QtGui.QLabel(Cobranzas)
        self.label_Concepto.setText(_fromUtf8(""))
        self.label_Concepto.setObjectName(_fromUtf8("label_Concepto"))
        self.horizontalLayout_3.addWidget(self.label_Concepto)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(Cobranzas)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.cmpPoliza = QtGui.QLineEdit(Cobranzas)
        self.cmpPoliza.setObjectName(_fromUtf8("cmpPoliza"))
        self.horizontalLayout_8.addWidget(self.cmpPoliza)
        self.btnPolizas = QtGui.QPushButton(Cobranzas)
        self.btnPolizas.setObjectName(_fromUtf8("btnPolizas"))
        self.horizontalLayout_8.addWidget(self.btnPolizas)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_5 = QtGui.QLabel(Cobranzas)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_7.addLayout(self.verticalLayout)
        self.cmpPlainTextPolizas = QtGui.QPlainTextEdit(Cobranzas)
        self.cmpPlainTextPolizas.setObjectName(_fromUtf8("cmpPlainTextPolizas"))
        self.horizontalLayout_7.addWidget(self.cmpPlainTextPolizas)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_Poliza = QtGui.QLabel(Cobranzas)
        self.label_Poliza.setText(_fromUtf8(""))
        self.label_Poliza.setObjectName(_fromUtf8("label_Poliza"))
        self.verticalLayout_2.addWidget(self.label_Poliza)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(Cobranzas)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.comboBoxOrganizador = QtGui.QComboBox(Cobranzas)
        self.comboBoxOrganizador.setObjectName(_fromUtf8("comboBoxOrganizador"))
        self.horizontalLayout_4.addWidget(self.comboBoxOrganizador)
        self.label_7 = QtGui.QLabel(Cobranzas)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_4.addWidget(self.label_7)
        self.cmpMatricula = QtGui.QLineEdit(Cobranzas)
        self.cmpMatricula.setObjectName(_fromUtf8("cmpMatricula"))
        self.horizontalLayout_4.addWidget(self.cmpMatricula)
        self.label_Matricula = QtGui.QLabel(Cobranzas)
        self.label_Matricula.setText(_fromUtf8(""))
        self.label_Matricula.setObjectName(_fromUtf8("label_Matricula"))
        self.horizontalLayout_4.addWidget(self.label_Matricula)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_8 = QtGui.QLabel(Cobranzas)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_5.addWidget(self.label_8)
        self.comboBoxCiaId = QtGui.QComboBox(Cobranzas)
        self.comboBoxCiaId.setObjectName(_fromUtf8("comboBoxCiaId"))
        self.horizontalLayout_5.addWidget(self.comboBoxCiaId)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_9 = QtGui.QLabel(Cobranzas)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_6.addWidget(self.label_9)
        self.cmpImporte = QtGui.QLineEdit(Cobranzas)
        self.cmpImporte.setObjectName(_fromUtf8("cmpImporte"))
        self.horizontalLayout_6.addWidget(self.cmpImporte)
        self.label_Importe = QtGui.QLabel(Cobranzas)
        self.label_Importe.setText(_fromUtf8(""))
        self.label_Importe.setObjectName(_fromUtf8("label_Importe"))
        self.horizontalLayout_6.addWidget(self.label_Importe)
        self.comboBoxImporteTipo = QtGui.QComboBox(Cobranzas)
        self.comboBoxImporteTipo.setObjectName(_fromUtf8("comboBoxImporteTipo"))
        self.horizontalLayout_6.addWidget(self.comboBoxImporteTipo)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10.addLayout(self.verticalLayout_3)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem5)
        self.btnAceptar = QtGui.QPushButton(Cobranzas)
        self.btnAceptar.setObjectName(_fromUtf8("btnAceptar"))
        self.horizontalLayout_9.addWidget(self.btnAceptar)
        self.btnCancelar = QtGui.QPushButton(Cobranzas)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.horizontalLayout_9.addWidget(self.btnCancelar)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_11.addLayout(self.verticalLayout_4)

        self.retranslateUi(Cobranzas)
        QtCore.QMetaObject.connectSlotsByName(Cobranzas)

    def retranslateUi(self, Cobranzas):
        Cobranzas.setWindowTitle(_translate("Cobranzas", "Dialog", None))
        self.label.setText(_translate("Cobranzas", "Tipo de registro", None))
        self.label_2.setText(_translate("Cobranzas", "Fecha de registro", None))
        self.label_3.setText(_translate("Cobranzas", "Concepto", None))
        self.label_4.setText(_translate("Cobranzas", "Poliza", None))
        self.btnPolizas.setText(_translate("Cobranzas", "Agregar", None))
        self.label_5.setText(_translate("Cobranzas", "Polizas", None))
        self.label_6.setText(_translate("Cobranzas", "Organizador", None))
        self.label_7.setText(_translate("Cobranzas", "Matricula", None))
        self.label_8.setText(_translate("Cobranzas", "Compañia", None))
        self.label_9.setText(_translate("Cobranzas", "Importe", None))
        self.btnAceptar.setText(_translate("Cobranzas", "Aceptar", None))
        self.btnCancelar.setText(_translate("Cobranzas", "Cancelar", None))

