# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tablapba.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(900, 600)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralWidget)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setMargin(11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setMargin(11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.label_TipoPersona = QtGui.QLabel(self.centralWidget)
        self.label_TipoPersona.setObjectName(_fromUtf8("label_TipoPersona"))
        self.horizontalLayout_2.addWidget(self.label_TipoPersona)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setMargin(11)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_2 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_3.addWidget(self.label_2)
        self.label_Matricula = QtGui.QLabel(self.centralWidget)
        self.label_Matricula.setObjectName(_fromUtf8("label_Matricula"))
        self.horizontalLayout_3.addWidget(self.label_Matricula)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setMargin(11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.centralWidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.label_CantReg = QtGui.QLabel(self.centralWidget)
        self.label_CantReg.setObjectName(_fromUtf8("label_CantReg"))
        self.horizontalLayout_4.addWidget(self.label_CantReg)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabla = QtGui.QTableWidget(self.centralWidget)
        self.tabla.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tabla.setObjectName(_fromUtf8("tabla"))
        self.tabla.setColumnCount(0)
        self.tabla.setRowCount(0)
        self.verticalLayout.addWidget(self.tabla)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setMargin(11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnUpdateReg = QtGui.QPushButton(self.centralWidget)
        self.btnUpdateReg.setObjectName(_fromUtf8("btnUpdateReg"))
        self.horizontalLayout.addWidget(self.btnUpdateReg)
        self.btnDelete = QtGui.QPushButton(self.centralWidget)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.horizontalLayout.addWidget(self.btnDelete)
        spacerItem1 = QtGui.QSpacerItem(138, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 25))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuArchivo = QtGui.QMenu(self.menuBar)
        self.menuArchivo.setObjectName(_fromUtf8("menuArchivo"))
        self.menuVer = QtGui.QMenu(self.menuBar)
        self.menuVer.setObjectName(_fromUtf8("menuVer"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.actionAbrir_archivo = QtGui.QAction(MainWindow)
        self.actionAbrir_archivo.setObjectName(_fromUtf8("actionAbrir_archivo"))
        self.actionAgregar_archivo_xml = QtGui.QAction(MainWindow)
        self.actionAgregar_archivo_xml.setObjectName(_fromUtf8("actionAgregar_archivo_xml"))
        self.actionGuardar = QtGui.QAction(MainWindow)
        self.actionGuardar.setObjectName(_fromUtf8("actionGuardar"))
        self.actionTodos_los_registros = QtGui.QAction(MainWindow)
        self.actionTodos_los_registros.setObjectName(_fromUtf8("actionTodos_los_registros"))
        self.actionResponsabilidad_civil = QtGui.QAction(MainWindow)
        self.actionResponsabilidad_civil.setObjectName(_fromUtf8("actionResponsabilidad_civil"))
        self.actionGuardar_como = QtGui.QAction(MainWindow)
        self.actionGuardar_como.setObjectName(_fromUtf8("actionGuardar_como"))
        self.actionAgregar_registro = QtGui.QAction(MainWindow)
        self.actionAgregar_registro.setObjectName(_fromUtf8("actionAgregar_registro"))
        self.actionGuardar_como_docx = QtGui.QAction(MainWindow)
        self.actionGuardar_como_docx.setObjectName(_fromUtf8("actionGuardar_como_docx"))
        self.menuArchivo.addAction(self.actionAbrir_archivo)
        self.menuArchivo.addAction(self.actionAgregar_archivo_xml)
        self.menuArchivo.addAction(self.actionAgregar_registro)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionGuardar_como)
        self.menuArchivo.addAction(self.actionGuardar_como_docx)
        self.menuVer.addAction(self.actionTodos_los_registros)
        self.menuVer.addAction(self.actionResponsabilidad_civil)
        self.menuBar.addAction(self.menuArchivo.menuAction())
        self.menuBar.addAction(self.menuVer.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Tipo Persona: ", None))
        self.label_TipoPersona.setText(_translate("MainWindow", "--", None))
        self.label_2.setText(_translate("MainWindow", "Matricula:", None))
        self.label_Matricula.setText(_translate("MainWindow", "--", None))
        self.label_3.setText(_translate("MainWindow", "Cantidad de registros:", None))
        self.label_CantReg.setText(_translate("MainWindow", "--", None))
        self.btnUpdateReg.setText(_translate("MainWindow", "Actualizar fecha de registro", None))
        self.btnDelete.setText(_translate("MainWindow", "Borrar registro", None))
        self.menuArchivo.setTitle(_translate("MainWindow", "Archivo", None))
        self.menuVer.setTitle(_translate("MainWindow", "Ver", None))
        self.actionAbrir_archivo.setText(_translate("MainWindow", "Abrir archivo xml...", None))
        self.actionAgregar_archivo_xml.setText(_translate("MainWindow", "Agregar archivo xml", None))
        self.actionGuardar.setText(_translate("MainWindow", "Guardar como...", None))
        self.actionTodos_los_registros.setText(_translate("MainWindow", "Todos los registros", None))
        self.actionResponsabilidad_civil.setText(_translate("MainWindow", "Responsabilidad civil", None))
        self.actionGuardar_como.setText(_translate("MainWindow", "Guardar como...", None))
        self.actionAgregar_registro.setText(_translate("MainWindow", "Agregar registro", None))
        self.actionGuardar_como_docx.setText(_translate("MainWindow", "Guardar como docx", None))

