# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogadd.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogAdd(object):
    def setupUi(self, DialogAdd):
        DialogAdd.setObjectName(_fromUtf8("DialogAdd"))
        DialogAdd.resize(900, 900)
        self.verticalLayout_8 = QtGui.QVBoxLayout(DialogAdd)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.scrollArea = QtGui.QScrollArea(DialogAdd)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -73, 864, 953))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.cmpFechaRegistro = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpFechaRegistro.setObjectName(_fromUtf8("cmpFechaRegistro"))
        self.horizontalLayout.addWidget(self.cmpFechaRegistro)
        self.label_FechaRegistro = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_FechaRegistro.setText(_fromUtf8(""))
        self.label_FechaRegistro.setObjectName(_fromUtf8("label_FechaRegistro"))
        self.horizontalLayout.addWidget(self.label_FechaRegistro)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.label_2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_2.addWidget(self.label_3)
        self.comboBoxTipoPersona = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxTipoPersona.setObjectName(_fromUtf8("comboBoxTipoPersona"))
        self.horizontalLayout_2.addWidget(self.comboBoxTipoPersona)
        self.label_4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBoxTipoDoc = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxTipoDoc.setObjectName(_fromUtf8("comboBoxTipoDoc"))
        self.horizontalLayout_2.addWidget(self.comboBoxTipoDoc)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_18.addWidget(self.label_5)
        self.cmpNroDoc = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpNroDoc.setObjectName(_fromUtf8("cmpNroDoc"))
        self.horizontalLayout_18.addWidget(self.cmpNroDoc)
        self.label_NroDoc = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_NroDoc.setText(_fromUtf8(""))
        self.label_NroDoc.setObjectName(_fromUtf8("label_NroDoc"))
        self.horizontalLayout_18.addWidget(self.label_NroDoc)
        self.verticalLayout_4.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_4.addWidget(self.label_6)
        self.cmpNombre = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpNombre.setObjectName(_fromUtf8("cmpNombre"))
        self.horizontalLayout_4.addWidget(self.cmpNombre)
        self.label_Nombre = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Nombre.setText(_fromUtf8(""))
        self.label_Nombre.setObjectName(_fromUtf8("label_Nombre"))
        self.horizontalLayout_4.addWidget(self.label_Nombre)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_15.addLayout(self.verticalLayout)
        self.cmpAsegurados = QtGui.QPlainTextEdit(self.scrollAreaWidgetContents)
        self.cmpAsegurados.setObjectName(_fromUtf8("cmpAsegurados"))
        self.horizontalLayout_15.addWidget(self.cmpAsegurados)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_19.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.btnAsegurado = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnAsegurado.setObjectName(_fromUtf8("btnAsegurado"))
        self.horizontalLayout_3.addWidget(self.btnAsegurado)
        self.label_Asegurados = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Asegurados.setText(_fromUtf8(""))
        self.label_Asegurados.setObjectName(_fromUtf8("label_Asegurados"))
        self.horizontalLayout_3.addWidget(self.label_Asegurados)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_8 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout_22.addWidget(self.label_8)
        self.cmpCPAP = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpCPAP.setObjectName(_fromUtf8("cmpCPAP"))
        self.horizontalLayout_22.addWidget(self.cmpCPAP)
        self.label_CPAP = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_CPAP.setText(_fromUtf8(""))
        self.label_CPAP.setObjectName(_fromUtf8("label_CPAP"))
        self.horizontalLayout_22.addWidget(self.label_CPAP)
        self.verticalLayout_6.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_9 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_2.addWidget(self.label_9)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_16.addLayout(self.verticalLayout_2)
        self.cmpObsProp = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.cmpObsProp.setObjectName(_fromUtf8("cmpObsProp"))
        self.horizontalLayout_16.addWidget(self.cmpObsProp)
        self.verticalLayout_6.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_10 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_5.addWidget(self.label_10)
        self.cmpCPACant = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpCPACant.setObjectName(_fromUtf8("cmpCPACant"))
        self.horizontalLayout_5.addWidget(self.cmpCPACant)
        self.label_CPACant = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_CPACant.setText(_fromUtf8(""))
        self.label_CPACant.setObjectName(_fromUtf8("label_CPACant"))
        self.horizontalLayout_5.addWidget(self.label_CPACant)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_11 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_6.addWidget(self.label_11)
        self.cmpCodPos = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpCodPos.setObjectName(_fromUtf8("cmpCodPos"))
        self.horizontalLayout_6.addWidget(self.cmpCodPos)
        self.btnCodigo = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnCodigo.setObjectName(_fromUtf8("btnCodigo"))
        self.horizontalLayout_6.addWidget(self.btnCodigo)
        self.label_Codigos = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Codigos.setText(_fromUtf8(""))
        self.label_Codigos.setObjectName(_fromUtf8("label_Codigos"))
        self.horizontalLayout_6.addWidget(self.label_Codigos)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_3.addWidget(self.label_12)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.horizontalLayout_17.addLayout(self.verticalLayout_3)
        self.cmpCodigos = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.cmpCodigos.setObjectName(_fromUtf8("cmpCodigos"))
        self.horizontalLayout_17.addWidget(self.cmpCodigos)
        self.verticalLayout_6.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_13 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_7.addWidget(self.label_13)
        self.comboBoxOrganizador = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxOrganizador.setObjectName(_fromUtf8("comboBoxOrganizador"))
        self.horizontalLayout_7.addWidget(self.comboBoxOrganizador)
        self.label_14 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_7.addWidget(self.label_14)
        self.cmpMatriculaOrg = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpMatriculaOrg.setObjectName(_fromUtf8("cmpMatriculaOrg"))
        self.horizontalLayout_7.addWidget(self.cmpMatriculaOrg)
        self.label_Matricula = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_Matricula.setText(_fromUtf8(""))
        self.label_Matricula.setObjectName(_fromUtf8("label_Matricula"))
        self.horizontalLayout_7.addWidget(self.label_Matricula)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.label_15 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_9.addWidget(self.label_15)
        self.comboBoxCiaId = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxCiaId.setObjectName(_fromUtf8("comboBoxCiaId"))
        self.horizontalLayout_9.addWidget(self.comboBoxCiaId)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_16 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_8.addWidget(self.label_16)
        self.cmpBienAseg = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpBienAseg.setObjectName(_fromUtf8("cmpBienAseg"))
        self.horizontalLayout_8.addWidget(self.cmpBienAseg)
        self.label_BienAseg = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_BienAseg.setText(_fromUtf8(""))
        self.label_BienAseg.setObjectName(_fromUtf8("label_BienAseg"))
        self.horizontalLayout_8.addWidget(self.label_BienAseg)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.label_17 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_11.addWidget(self.label_17)
        self.comboBoxRamo = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxRamo.setObjectName(_fromUtf8("comboBoxRamo"))
        self.horizontalLayout_11.addWidget(self.comboBoxRamo)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_18 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_10.addWidget(self.label_18)
        self.cmpSumaAseg = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpSumaAseg.setObjectName(_fromUtf8("cmpSumaAseg"))
        self.horizontalLayout_10.addWidget(self.cmpSumaAseg)
        self.label_SumaAseg = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_SumaAseg.setText(_fromUtf8(""))
        self.label_SumaAseg.setObjectName(_fromUtf8("label_SumaAseg"))
        self.horizontalLayout_10.addWidget(self.label_SumaAseg)
        self.comboBoxSumaTipo = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxSumaTipo.setObjectName(_fromUtf8("comboBoxSumaTipo"))
        self.horizontalLayout_10.addWidget(self.comboBoxSumaTipo)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_23.addLayout(self.verticalLayout_6)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.label_19 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_7.addWidget(self.label_19)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_20 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_12.addWidget(self.label_20)
        self.cmpFechaDes = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpFechaDes.setObjectName(_fromUtf8("cmpFechaDes"))
        self.horizontalLayout_12.addWidget(self.cmpFechaDes)
        self.label_FechaDes = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_FechaDes.setText(_fromUtf8(""))
        self.label_FechaDes.setObjectName(_fromUtf8("label_FechaDes"))
        self.horizontalLayout_12.addWidget(self.label_FechaDes)
        self.label_21 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_12.addWidget(self.label_21)
        self.cmpFechaHas = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpFechaHas.setObjectName(_fromUtf8("cmpFechaHas"))
        self.horizontalLayout_12.addWidget(self.cmpFechaHas)
        self.label_FechaHas = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_FechaHas.setText(_fromUtf8(""))
        self.label_FechaHas.setObjectName(_fromUtf8("label_FechaHas"))
        self.horizontalLayout_12.addWidget(self.label_FechaHas)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_23 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_24.addWidget(self.label_23)
        self.comboBoxTipoOp = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxTipoOp.setObjectName(_fromUtf8("comboBoxTipoOp"))
        self.horizontalLayout_24.addWidget(self.comboBoxTipoOp)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem7)
        self.verticalLayout_5.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_25 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_21.addWidget(self.label_25)
        self.cmpPoliza = QtGui.QLineEdit(self.scrollAreaWidgetContents)
        self.cmpPoliza.setObjectName(_fromUtf8("cmpPoliza"))
        self.horizontalLayout_21.addWidget(self.cmpPoliza)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem8)
        self.verticalLayout_5.addLayout(self.horizontalLayout_21)
        self.checkBoxFlota = QtGui.QCheckBox(self.scrollAreaWidgetContents)
        self.checkBoxFlota.setObjectName(_fromUtf8("checkBoxFlota"))
        self.verticalLayout_5.addWidget(self.checkBoxFlota)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_22 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_14.addWidget(self.label_22)
        self.comboBoxContacto = QtGui.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxContacto.setObjectName(_fromUtf8("comboBoxContacto"))
        self.horizontalLayout_14.addWidget(self.comboBoxContacto)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_14)
        spacerItem9 = QtGui.QSpacerItem(238, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem9)
        self.verticalLayout_5.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_25.addLayout(self.verticalLayout_5)
        spacerItem10 = QtGui.QSpacerItem(29, 88, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.btnAceptar = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnAceptar.setObjectName(_fromUtf8("btnAceptar"))
        self.horizontalLayout_13.addWidget(self.btnAceptar)
        self.btnCancelar = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.btnCancelar.setObjectName(_fromUtf8("btnCancelar"))
        self.horizontalLayout_13.addWidget(self.btnCancelar)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.label_2.raise_()
        self.label_19.raise_()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.scrollArea.raise_()
        self.label_23.raise_()
        self.label_25.raise_()
        self.comboBoxTipoOp.raise_()
        self.cmpPoliza.raise_()
        self.checkBoxFlota.raise_()

        self.retranslateUi(DialogAdd)
        QtCore.QMetaObject.connectSlotsByName(DialogAdd)

    def retranslateUi(self, DialogAdd):
        DialogAdd.setWindowTitle(_translate("DialogAdd", "Dialog", None))
        self.label.setText(_translate("DialogAdd", "Fecha de Registro", None))
        self.label_2.setText(_translate("DialogAdd", "Asegurado", None))
        self.label_3.setText(_translate("DialogAdd", "Tipo persona", None))
        self.label_4.setText(_translate("DialogAdd", "Tipo doc.", None))
        self.label_5.setText(_translate("DialogAdd", "Nro. Documento", None))
        self.label_6.setText(_translate("DialogAdd", "Nombre", None))
        self.label_7.setText(_translate("DialogAdd", "Agregados", None))
        self.btnAsegurado.setText(_translate("DialogAdd", "Agregar", None))
        self.label_8.setText(_translate("DialogAdd", "CPA Proponente", None))
        self.label_9.setText(_translate("DialogAdd", "Obs. Proponente", None))
        self.label_10.setText(_translate("DialogAdd", "CPA Cantidad", None))
        self.label_11.setText(_translate("DialogAdd", "Codigo postal", None))
        self.btnCodigo.setText(_translate("DialogAdd", "Agregar", None))
        self.label_12.setText(_translate("DialogAdd", "Codigos postales", None))
        self.label_13.setText(_translate("DialogAdd", "Organizador", None))
        self.label_14.setText(_translate("DialogAdd", "Matricula", None))
        self.label_15.setText(_translate("DialogAdd", "Compania", None))
        self.label_16.setText(_translate("DialogAdd", "Bien asegurado", None))
        self.label_17.setText(_translate("DialogAdd", "Ramo", None))
        self.label_18.setText(_translate("DialogAdd", "Suma asegurada", None))
        self.label_19.setText(_translate("DialogAdd", "Cobertura", None))
        self.label_20.setText(_translate("DialogAdd", "Fecha desde", None))
        self.label_21.setText(_translate("DialogAdd", "Fecha hasta", None))
        self.label_23.setText(_translate("DialogAdd", "Tipo operacion", None))
        self.label_25.setText(_translate("DialogAdd", "Poliza", None))
        self.checkBoxFlota.setText(_translate("DialogAdd", "Flota", None))
        self.label_22.setText(_translate("DialogAdd", "Tipo de contacto", None))
        self.btnAceptar.setText(_translate("DialogAdd", "Aceptar", None))
        self.btnCancelar.setText(_translate("DialogAdd", "Cancelar", None))

